# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Invoswift-Mern CI

on: [pull_request]

jobs:
  root:
    name: Invoswift-mern-jobs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Root install Step
        id: root_installs
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g yarn
      - run: npm i

      - name: Server Step
        id: server_installs
        run: echo "Server Step"
      - run: cd ./server && pwd && npm i

      - name: Client Step
        id: client_installs
        run: echo "Client Step"
      - run: cd ./client && pwd && npm i
      - run: cd ./client && pwd && npm run build

      - name: Admin template Step
        id: admin_installs
        run: echo "Admin Template Step"
      - run: cd ./admin && pwd && yarn
      - run: cd ./admin && pwd && CI= true yarn build --verbose